language: ruby
rvm:
  - 2.3.0
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3

before_install: gem install bundler -v 1.11.2

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile

script: "bundle exec rake spec"
